### ISSUE TITLE
xCall Future Proof Messaging

### ISSUE THREAD

**Issue by pragyanshrestha-ibriz** [icon-project/xcall-multi#177]
### What needs to be done

Please check - https://github.com/icon-project/ibc-planning/issues/273 for details

**Comment by FezBox** [comment]
how come this has been closed when a lot of the stories in it is still in progress @pragyanshrestha-ibriz

**Comment by pragyanshrestha-ibriz** [comment]
@FezBox  hmm might have confused the epic wth the story.. repoening.
