### ISSUE TITLE
refactor EVM contract for sample dapp

### ISSUE THREAD

**Issue by FidelVe** [icon-project/xcall-multi#197]
### What needs to be done

The EVM contract for the sample dapp found here:
https://github.com/icon-project/xcall-multi/blob/main/contracts/evm/contracts/mocks/dapp/DAppProxySample.sol

The logic for the rollback should be refactored following the bug found in the issue for the JVM contract here
https://github.com/icon-project/xcall-multi/issues/194

**Comment by pragyanshrestha-ibriz** [comment]
the  issue has been resolved.
