### ISSUE TITLE
E2E testing for new xCall messages

### ISSUE THREAD

**Issue by AntonAndell** [icon-project/xcall-multi#225]
E2E testing for new xCall messages
Extend/fork example dapps to be able to respond to messages for testing/demo purposes. Forked dapps use the new message types when responding and sending messages. 

Divided into issues #235 #236 #237

**Comment by pragyanshrestha-ibriz** [comment]
Can be done for IBC and Central relay for now.

**Comment by bcsainju** [comment]
The future proofing feature hasn't been merged to main yet. So, will send PR after the changes are merged.
